service: wfm-single
image: minamoto64/wfm-single

servers:
  web:
    - 54.178.174.111

ssh:
  user: ubuntu

proxy:
  ssl: true
  host: sync-wfm.com
  app_port: 80
  healthcheck:
    path: /up
    interval: 3
    timeout: 30

registry:
  server: ghcr.io
  username: minamoto64
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
  clear:
    SOLID_QUEUE_IN_PUMA: true
    JOB_CONCURRENCY: 1
    RAILS_MAX_THREADS: 5
    RAILS_LOG_LEVEL: info
    APP_HOST: sync-wfm.com

accessories:
  db:
    image: postgres:17
    host: 54.178.174.111
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: wfm_single
        POSTGRES_DB: wfm_single_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

volumes:
  - "wfm_single_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
  cache:
    type: gha

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"
  demo-reset: app exec "bin/rails demo:reset"
  db-dump: accessory exec db "pg_dump -U wfm_single -d wfm_single_production" --reuse
